title: "Dwequieve Davis"
description: "Cybersecurity student | Digital Forensics | Blog + Bio"
theme: minima
markdown: kramdown

collections:
  posts:
    output: true

minima:
  skin: classic
  custom_css:
    - /assets/css/custom.css
  social_links:
    - { platform: handshake, user_url: "https://app.joinhandshake.com/profiles/u7ujtr" }

show_excerpts: true
